server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://node6:3306/etl_db?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: leo
    password: Yyf5211314!
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 1000
      max-active: 30
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000
      max-idle: 30
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
  output:
    ansi:
      enabled: detect
logging:
  path: logs/
  file: logs/LeoFastKettle.log


